# Generated by Django 3.2 on 2021-12-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('directs', models.CharField(max_length=50)),
                ('s_manager', models.CharField(max_length=50)),
                ('consolidated_teams', models.CharField(max_length=50)),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgChartApp.channel')),
                ('consolidated_primary_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgChartApp.team')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrgChartApp.user')),
            ],
        ),
    ]
