# Generated by Django 3.2 on 2021-12-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrgChartApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='channel_id',
        ),
        migrations.AddField(
            model_name='team',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgChartApp.channel'),
        ),
        migrations.AlterField(
            model_name='team',
            name='consolidated_primary_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OrgChartApp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='consolidated_teams',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
